name: CI

on: [issues, issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: install dependencies
      run: |
        pip3 install setuptools --user
        pip3 install PyGithub --user
        pip3 install wordcloud --user
        pip3 install matplotlib --user
    - name: run python script
      env:
        GITHUB_LOGIN: iamtomas
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 main.py
    - name: config git info
      run: |
        git config --global user.email "867493059@qq.com"
        git config --global user.name "iamtomas"
    - name: commit change
      run: |
        git checkout master
        git add .
        git commit -m "Update from Github Action"
    - name: push change
      env:
        GITHUB_LOGIN: iamtomas
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch
        git rebase origin/master
        git push origin master:master
    - name: done
      run: echo 'done'
